comments/urls.py
from django.urls import path
from . import views

app_name ='comments'

urlpatterns = [
    path('', views.comments)
]

foodie/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sandbox/', include('sandbox.urls')),
    path('', include('foodie_app.urls')),
    path('recipes/', include('recipes.urls')),
    path('comments/', include('comments.urls')),
]

foodie_app/urls.py
from django.urls import path

from foodie_app  import views


app_name = 'foodie_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('recipes/<int:category_id>', views.recipes, name='recipes'),   
]

recipes/urls.py
from django.urls import path
from recipes import views

app_name = 'recipes'
urlpatterns = [
    path('', views.recipes, name='index'),
    path('<int:recipe_id>', views.recipe, name='recipe_detail'),
]

sandbox/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path( '', views.index),
]

comments/models.py
from django.db import models
from recipes.models import Recipe

# Create your models here.
class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    comment = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    
    def __str__(self):
        return self.comment

foodie_app/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    date_added = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.name

recipes/models.py
from django.db import models
from foodie_app.models import Category

# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    ingridients = models.TextField()
    instructions = models.TextField()
    posted_on = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

sandbox/models.py
from django.db import models

# Create your models here.

comments/views.py
from django.shortcuts import render

# Create your views here.
def comments(request):
    return render(request, 'comments/comments.html')

foodie_app/views.py
from django.shortcuts import render
from .models import Category
from recipes.models import Recipe

def index(request):
    template ='foodie_app/index.html'
    categories = Category.objects.all()
    context ={'categories': categories}
    
    return render(request, template, context)

def recipes(request, category_id):
    template ='foodie_app/recipes.html'
    recipes = Recipe.objects.filter(category=category_id)
    category = Category.objects.get(pk=category_id)
    context ={'recipes': recipes, 'category': category}
    
    return render(request, template, context)

recipes/views.py
from django.shortcuts import render
from .models import Recipe

# Create your views here.
def recipes(request):
    recipes = Recipe.objects.all()
    template = 'recipes/recipes.html'
    context ={'recipes': recipes}
    return render(request, template, context)

def recipe(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    tempate = 'recipes/recipe.html'
    context ={'recipe': recipe}
    return render(request, tempate, context)

sandbox/views.py
from django.shortcuts import render


def index(request):
    
    data = ['apple', 'banana', 'carrot', 'date', 'eggplant']
    context = {'foods': data}
    return render(request, 'sandbox/index.html', context)

comments/templates/comments/comments.html
{% extends "base.html" %}

{% block content %}
    it's comments page
{% endblock content %}

foodie_app/templates/foodie_app/index.html
{% extends "base.html" %}

{% block content %}
<h3>Categories</h3>

    
    <div>
         {% for category in categories %}
        <div>
              <a href="{% url "foodie_app:recipes" category.id %}">{{ category.name }}</a>
        </div>
         {% endfor %}
    </div>
   

{% endblock content %}

foodie_app/templates/foodie_app/recipes.html
{% extends "base.html" %}

{% block content %}
<h3>Recipes Under <em>{{category}} </em></h3>

    
    <div>
         {% for recipe in recipes %}
        <div>
            <div>
                <h5>
                    {{recipe.name}}
                </h5>
                <p>{{recipe.description}} </p>
            </div>
              <!-- <a href="{% url "recipes:index" %}">{{ category.name }}</a> -->
        </div>
         {% endfor %}
    </div>
   

{% endblock content %}

recipes/templates/recipes/recipe.html
{% extends "base.html" %}

{% block content %}
    <div>
        <h5>{{recipe.name}}</h5>
        <i>description:</i>
        <p>{{recipe.description}}</p>
        <i>Ingridients:</i>
        <p>{{recipe.ingridients}} </p>
        <i>Instructions:</i>
        <p>{{recipe.instructions}}</p>

    </div>
{% endblock content %}

recipes/templates/recipes/recipes.html
{% extends "base.html" %}

{% block content %}
<div>
    {%for recipe in recipes %}
    <div>
        <h5>{{recipe.name}}</h5>
        <p>{{recipe.description}}</p>
        <a href="{% url "recipes:recipe_detail" recipe.id %}">View Recipe Details</a>
    </div>
    {%endfor%}
</div>
{% endblock content %}

sandbox/templates/sandbox/index.html
{% extends "base.html" %}

{% block content %}
    {% if foods %}
        <ul>
            {% for food in foods %}
                <li>{{ food }}</li>
          
            {% endfor %}
        </ul>
        {% else %}
        <p>No foods available</p>
    {% endif %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Foodies</title>
    </head>
    <body>
        <nav>
            <div>
                <p><a href="{% url "foodie_app:index" %}">Home</a></p>
            </div>
        </nav>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
        <hr>
        <footer>
            <pre>Footer</pre>
        </footer>
    </body>
</html>